/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false ./src/@types/worker-configuration.d.ts` (hash: 864bcec6d2ad01b7ce914accccb1dfba)
declare namespace Cloudflare {
	interface Env {
		ADMIN_KV: KVNamespace;
		MAIN_KV: KVNamespace;
		NODE_VERSION: "23";
		ENVIRONMENT: string;
		AUTH_SESSION_SECRET_KEY: string;
		CSRF_COOKIE_SECRET_KEY: string;
		HONEYPOT_SECRET_KEY: string;
		TOAST_COOKIE_SECRET_KEY: string;
		TOTP_SECRET_KEY: string;
		EMAIL_API_KEY: string;
		MAIN_D1: D1Database;
		RATE_LIMITER: RateLimit;
	}
}
interface Env extends Cloudflare.Env {}
